services:
  weatherwear:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weatherwear
    environment:
      - API_KEY_WEATHERAPI=${API_KEY_WEATHERAPI}
      - AUTH_SPOTIFY_CLIENT_ID=${AUTH_SPOTIFY_CLIENT_ID}
      - AUTH_SPOTIFY_CLIENT_SECRET=${AUTH_SPOTIFY_CLIENT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - dbnet
      - redisnet

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - DB_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    depends_on:
      - redis
    networks:
      - dbnet

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - redisnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - dbnet

volumes:
  pgadmin:

networks:
  dbnet:
  redisnet:
